/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-126782-gdc52424419-20260923"
#endif /* AVUTIL_FFVERSION_H */
